[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
voting_system = "qdgqhajmT3X3eckTpbXJxTY2aG2ykERjkwoRejZ7hZF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/adityarola/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
